version: '3'
services:
  python:
    container_name: 'python-pytorch-skeleton'
    build:
      context: ..
      dockerfile: "python/Dockerfile"
    platform: linux/amd64 # for Apple Mac M1
    user: root
    tty: true
    volumes:
      - ../:/workplace:cached
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
