epochs: 20
batch_size: 4
logging_per_batch: 1000
valid_size: 0.1
test_size: 0.1
lr: 0.0001
lr_decay: 0.9
early_stop_patience: 15
threshold: 0.5
k_folds: 4
dataset_path: /workplace/pytorch_skeleton/data
weights_dir: /workplace/pytorch_skeleton/weights
log_dir: /workplace/pytorch_skeleton/logs
out_dir: /workplace/pytorch_skeleton/outputs

model: 
    name: dla34
    # hidden_dim: 300
    # dropout: 0.3

lr_finder:
    initial_value: 0.000000001
    final_value: 10.0
    beta: 0.98