k_folds: 4
epochs: 20
batch_size: 512
logging_per_batch: 1000
valid_size: 0.1
test_size: 0.1
lr: 0.0001
lr_decay: 0.9
early_stop_patience: 15
threshold: 0.5
dataset_path: /content/pytorch_skeleton/data
weights_dir: /content/pytorch_skeleton/weights
log_dir: /content/pytorch_skeleton/logs/log
log_filename: pytorch_skeleton.log
out_dir: /content/pytorch_skeleton/outputs

model: 
    name: dla34
    # hidden_dim: 300
    # dropout: 0.3

lr_finder:
    initial_value: 0.000000001
    final_value: 10.0
    beta: 0.98
